name: Validation

on:
  workflow_dispatch:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Release
  REST_PATH: /rest/tracklib/install
  TRACK_LIB_PATH: tracklib
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:

  libCheck:
    name: Validate library
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rest-for-physics/root:latest
    steps:
      - uses: rest-for-physics/framework/.github/actions/checkout@master
        with:
          branch: ${{ env.BRANCH_NAME }}
          repository: rest-for-physics/tracklib
          path: ${{ env.TRACK_LIB_PATH }}
      - run: python3 ${{ env.TRACK_LIB_PATH }}/pipeline/validateLibrary.py .

  precommit-config:
    name: Validate pre-commit config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rest-for-physics/root:latest
    steps:
      - name: Checkout tracklib
        uses: rest-for-physics/framework/.github/actions/checkout@master
        with:
          branch: ${{ env.BRANCH_NAME }}
          repository: rest-for-physics/tracklib
          path: ${{ env.TRACK_LIB_PATH }}
      - name: Verify pre-commit config files match
        run: |
          cd ${{ env.TRACK_LIB_PATH }}
          curl https://raw.githubusercontent.com/rest-for-physics/framework/master/scripts/validatePreCommitConfig.py | python

  build-tracklib:
    name: Build only tracklib
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rest-for-physics/root:latest
    steps:
      - name: Build and install
        uses: rest-for-physics/framework/.github/actions/build@master
        with:
          cmake-flags: "-DCMAKE_INSTALL_PREFIX=${{ env.REST_PATH }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DREST_WELCOME=ON -DRESTLIB_TRACK=ON"
          branch: ${{ env.BRANCH_NAME }}
      - name: Load REST libraries
        run: |
          source ${{ env.REST_PATH }}/thisREST.sh
          restRoot -b -q
